server:
  port: 8888

spring:
  application:
    name: balance-game-back

  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    url: ENC(1cyyQ/RpeXUSqqHniFsPZ73sKafsovk8laIVFUIVeBH5oR0MYZ+99v3pEXIN3Mk7OEjYmTztxXZhbwQnI+Ccp9XBu5cAt3x3Fj0smgntNsf3MJpMeI5E6MeQN+mKcc2r)
    username: ENC(/CyspIvvF6dNHOEFtUrFTg==)
    password: ENC(iyfDvnpBLAn2JgPYybtabOmRY72ej6IB)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    redis:
      host: redis
      port: 6379

cloud:
  aws:
    s3:
      bucket: balance-game
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      accessKey: ENC(QiAuZ2EVou3O2rWWcbTL4D4K3u0xyR+I83y9lic55xE=)
      secretKey: ENC(WPfcWOajvrVSXhTa24QI6Vh7yufF/kT/xlLFh+BPR49qajaUGYnQW6vPu4c2nIDKO0qbhDJLoJ0=)
    stack:
      auto: false

jwt:
  secret:
  accessTokenExpiration: ENC(q2BMQ2xD6lIeY3k6v0a5pQ==)
  refreshTokenExpiration: ENC(Ctd7LwyetvJ/2VYebvIIaQ==)

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, beans, refresh, info, metrics, prometheus

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
